// SPDX-License-Identifier: MIT
// Rp2040LlvmCodeGen - lowers the architecture-agnostic PyMCU IR (ProgramIR)
// to LLVM IR text (.ll) for the RP2040 (ARM Cortex-M0+, thumbv6m-none-eabi).
//
// Design: emit textual LLVM IR (no LLVMSharp / native libLLVM dependency).
// Each named Variable / Temporary becomes an `alloca` + load/store; LLVM's
// mem2reg pass (run by `opt`) promotes them to SSA, and LLVM handles register
// allocation, instruction selection and the AAPCS calling convention.
//
// NOTE: Phase 1 scaffold. Compile() currently emits only the module preamble
// and per-function stubs; full instruction lowering lands in Phase 2.

using PyMCU.Common.Models;
using PyMCU.IR;

namespace PyMCU.Backend.Targets.RP2040;

public class Rp2040LlvmCodeGen(DeviceConfig cfg) : CodeGen
{
    // ARMv6-M, little-endian, 32-bit pointers. Matches `llc -mtriple=thumbv6m-none-eabi`.
    private const string TargetTriple = "thumbv6m-none-eabi";
    private const string DataLayout   = "e-m:e-p:32:32-Fi8-i64:64-v128:64:128-a:0:32-n32-S64";

    private readonly DeviceConfig _cfg = cfg;

    public override void Compile(ProgramIR program, TextWriter output)
    {
        EmitModulePreamble(output);

        foreach (var func in program.Functions)
        {
            // Phase 2 will lower func.Body. For now emit a recognizable stub so
            // the pipeline (CLI -> .ll -> opt -verify) is wired end to end.
            string name = SanitizeSymbol(func.Name);
            output.WriteLine();
            output.WriteLine($"; function {func.Name} ({func.Body.Count} IR instructions) - lowering pending");
            output.WriteLine($"define void @{name}() {{");
            output.WriteLine("entry:");
            output.WriteLine("  ret void");
            output.WriteLine("}");
        }
    }

    private void EmitModulePreamble(TextWriter output)
    {
        output.WriteLine("; PyMCU RP2040 backend - generated LLVM IR");
        output.WriteLine($"; target chip: {_cfg.TargetChip}  freq: {_cfg.Frequency} Hz");
        output.WriteLine($"target datalayout = \"{DataLayout}\"");
        output.WriteLine($"target triple = \"{TargetTriple}\"");
    }

    // Map a PyMCU IR symbol (which may contain '.') to a valid LLVM identifier body.
    private static string SanitizeSymbol(string name)
    {
        var chars = name.ToCharArray();
        for (int i = 0; i < chars.Length; i++)
        {
            char c = chars[i];
            bool ok = c is (>= 'a' and <= 'z') or (>= 'A' and <= 'Z')
                          or (>= '0' and <= '9') or '_';
            if (!ok) chars[i] = '_';
        }
        return new string(chars);
    }

    // RP2040 is a 32-bit Cortex-M0+; interrupt/context handling is generated by
    // the LLVM backend + crt0 runtime, not emitted here. These overrides exist
    // only to satisfy the CodeGen contract shared with the asm backends.
    public override void EmitContextSave() { }
    public override void EmitContextRestore() { }
    public override void EmitInterruptReturn() { }
}
